% feature-selection-mRMR
% Created by Jiahong K. Chen

% Input: 
%       dataX n-by-p, n is #observation, p is dim of feature
%       dataC n-by-1, the class of observations
%       nMRMR       , dimension of feature subspace generated by mRMR
%       classifier  , 'NB' or 'LDA'
% Output: candidate feature set

function candiFea = candidateFeature(dataX, dataC, nMRMR, classifier, errThres)

mrmrFea = mRMR(dataX, dataC, nMRMR);

kFold   = 10;

meanErr = zeros(nMRMR, 1);
varErr  = zeros(nMRMR, 1);
mt2Err  = zeros(nMRMR, 1);

for Sid = 1 : nMRMR

    feaIdx = mrmrFea(1:Sid);
    [meanErr(Sid) ,varErr(Sid), mt2Err(Sid)] = ...
        cvErrEst(dataX(:,feaIdx), dataC, classifier, kFold);

end

goodIdx         = find(mt2Err < errThres);

[~, greatIdx ]  = min( meanErr(goodIdx) );

candiFea        = mrmrFea( 1 : goodIdx(greatIdx) );

end